apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: '{{ .Values.username | b64enc }}'
  password: '{{ .Values.password | b64enc }}'

---

apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .password: '{{ .Values.password | b64enc }}' 